resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # Register a health indicator for the circuit breaker in Spring Boot Actuator.
        slidingWindowSize: 10 # Number of calls to consider when calculating the failure rate. The circuit breaker will evaluate the failure rate based on the last 'slidingWindowSize' calls.
        minimumNumberOfCalls: 3 # Minimum number of calls to evaluate the failure rate. If the number of calls is less than this value, the circuit breaker will not transition to open state, even if all calls fail.
        permittedNumberOfCallsInHalfOpenState: 2 # Number of calls that are allowed to pass through when the circuit breaker is in half-open state. If any of these calls fail, the circuit breaker will transition back to open state.
        automaticTransitionFromOpenToHalfOpenEnabled: true # Enable automatic transition from open to half-open state after the wait duration has passed.
        waitDurationInOpenState: 20000ms # Time that the circuit breaker should wait before transitioning from open to half-open state. During this time, all calls will be rejected.
        failureRateThreshold: 50 # Failure rate threshold in percentage. If the failure rate exceeds this threshold, the circuit breaker will transition to open state.
    instances:
      externalPaymentProcessor:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3 # Maximum number of retry attempts. The operation will be retried up to this number of times before giving up.
        waitDuration: 1000ms # Time to wait between retry attempts. This is the duration that the system will wait before making another attempt after a failure.
    instances:
      externalPaymentProcessor:
        baseConfig: default